In [1]:
import numpy as np

np.__version__

'1.21.0'

In [2]:
john = [10, 8, 6, 7]
x = np.array(john)

type(x)

numpy.ndarray

In [3]:
x

array([10,  8,  6,  7])

In [6]:
[john[i]+1 for i in range(4)]

[11, 9, 7, 8]

In [9]:
john = np.array(john)
john

array([10,  8,  6,  7])

In [10]:
john+1

array([11,  9,  7,  8])

#### 다차원 배열
- 넘파이는 다차원배열
- 파이썬 리스트

In [20]:
score = [[1.,2.,3.,4.],[5,6,7,8]]
x = np.array(score)
x

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [16]:
x.shape

(2, 4)

In [22]:
x.reshape(8,)

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [18]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
x.dtype

dtype('float64')

In [37]:
x = np.arange(1,10)
x.shape

(9,)

In [39]:
y = x.reshape(-1,3,3)
y

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [44]:
X = np.arange(0,16)
X = X.reshape(4,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
X = X.reshape(2,4,2)
X

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [52]:
x = np.array([1,2,3])
y = np.array([[1],[2],[3]])
x.shape,y.reshape(-1)

((3,), array([1, 2, 3]))

In [58]:
X = np.arange(0,16)
X = X.reshape(2,-1,2)
X

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

#### slicing, indexing

In [78]:
X = np.array([4,5,6,7,8,9])
X = X.reshape(2,3)
X

array([[4, 5, 6],
       [7, 8, 9]])

In [83]:
#fancy indexing
X[0,[1,2]]

array([5, 6])

In [85]:
X[0,1:]

array([5, 6])

In [86]:
#boolean indexing
X = np.arange(1,6)
idx = [False,True,True,True,False]
X[idx]

array([2, 3, 4])

In [90]:
X = np.array([1,9,2,4,7])
X[X > 6]

array([9, 7])

In [93]:
X = np.arange(1,7).reshape(3,2)
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [94]:
np.sum(X, axis = 0)

array([ 9, 12])

In [96]:
np.mean(X, axis = 0)

array([3., 4.])

In [99]:
X+1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [101]:
X = np.arange(1,4).reshape(3,1)
Y = np.arange(1,4)
X,Y

(array([[1],
        [2],
        [3]]),
 array([1, 2, 3]))

In [102]:
X+Y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [103]:
X.dtype

dtype('int32')

In [104]:
X.astype(np.float64)

array([[1.],
       [2.],
       [3.]])

#### 난수 생성 함수

##### np.random.random()
- (0.0,1.0)

In [2]:
import numpy as np

np.__version__

'1.21.0'

In [3]:
np.random.random(3)

array([0.94103926, 0.10613948, 0.52002573])

In [4]:
np.random.random((2,2))

array([[0.40668633, 0.14296836],
       [0.63631976, 0.58455817]])

In [7]:
# 같은 함수, 다른 표현
# random(), random_sample(), rand()

##### 정규분포 추출 randn()

In [9]:
np.random.seed(2022)
np.random.randn(3,2)

array([[-5.27899086e-04, -2.74901425e-01],
       [-1.39285562e-01,  1.98468616e+00],
       [ 2.82109326e-01,  7.60808658e-01]])

In [12]:
np.random.randint(2,23,(2,4))

array([[13, 21, 10, 13],
       [18, 21,  8, 10]])

In [16]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [17]:
x+y

array([[ 6,  8],
       [10, 12]])

In [18]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [23]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

#### 행렬연산 3가지

In [20]:
x@y

array([[19, 22],
       [43, 50]])

In [21]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [22]:
np.matmul(x,y)

array([[19, 22],
       [43, 50]])

In [25]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.matmul(x,y)

32

#### np.argmax()

In [36]:
x = np.random.randn(5, 4)
print(x)
np.argmax(x,axis=0)

[[-0.67028832 -0.53867632 -0.35305234  1.83166474]
 [ 0.68179401 -0.54893699 -0.08854093 -1.16177716]
 [ 0.04334993  0.28627855  0.31002766  1.01427196]
 [-0.53091456  1.11557556  0.7960597   0.2284146 ]
 [ 1.05977863 -0.49601602  0.18279691 -0.70413539]]


array([4, 3, 3, 0], dtype=int64)

#### 저장 savez()

In [38]:
x = np.random.randn(5,4)
y = np.random.randn(3,3)
x

array([[ 2.30035255, -1.69664595, -0.69035737, -0.07596383],
       [ 0.01659398,  0.48782301,  1.01276624,  0.51589934],
       [ 0.69230623,  1.16285432,  0.63859334, -0.00564434],
       [ 0.3505266 , -0.44776523, -1.09372529, -1.32020028],
       [ 0.34576926,  0.21349644,  0.81241333, -1.04453068]])

In [39]:
np.savez('mydata.npz', xvar=x, yvar = y)

#### 모델 생성

In [44]:
# 파일 로딩
 
mydata = np. load('mydata.npz')

In [45]:
x = mydata['xvar']
x

array([[ 2.30035255, -1.69664595, -0.69035737, -0.07596383],
       [ 0.01659398,  0.48782301,  1.01276624,  0.51589934],
       [ 0.69230623,  1.16285432,  0.63859334, -0.00564434],
       [ 0.3505266 , -0.44776523, -1.09372529, -1.32020028],
       [ 0.34576926,  0.21349644,  0.81241333, -1.04453068]])